/** Extract literal text from PDFs generated by createSimpleTextPdf (for tests). */
export function extractLiteralPdfText(pdf: Uint8Array): string {
  const raw = Buffer.from(pdf).toString("latin1");
  const chunks: string[] = [];
  const pattern = /\((?:\\.|[^\\)])*\)\s*Tj/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(raw)) !== null) {
    const inner = match[0].replace(/\)\s*Tj$/, "").slice(1);
    chunks.push(unescapePdfLiteral(inner));
  }
  return chunks.join(" ");
}

function unescapePdfLiteral(value: string): string {
  return value
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\b/g, "\b")
    .replace(/\\f/g, "\f")
    .replace(/\\\(/g, "(")
    .replace(/\\\)/g, ")")
    .replace(/\\\\/g, "\\");
}
