export type CompanySource = {
  name: string;
  categories: string[];
  priority: 1 | 2 | 3;
  searchTerms: string[];
  careersQuery: string;
  atsSlugs?: Partial<Record<"greenhouse" | "lever" | "ashby", string[]>>;
};

const defaultSearchTerms = [
  "Senior Frontend Engineer",
  "Staff Frontend Engineer",
  "Principal Frontend Engineer",
  "Senior Software Engineer, Frontend",
  "Senior Software Engineer, UI",
  "Senior Software Engineer, Web",
  "Senior Product Engineer",
  "Senior Full Stack Engineer",
  "Staff Full Stack Engineer",
  "Design Systems Engineer",
  "Frontend Platform Engineer",
  "Developer Experience Engineer",
  "Internal Tools Engineer",
  "Admin Console Engineer",
  "Enterprise UI Engineer",
  "React Engineer",
  "TypeScript Engineer",
  "Next.js Engineer",
];

const categoryTerms: Record<string, string[]> = {
  security: ["Authentication", "Identity", "Security", "Passkeys", "WebAuthn", "Compliance"],
  identity: ["Authentication", "Identity", "Authorization", "Access Management"],
  ai: ["AI Product Engineer", "Applied AI Engineer", "AI Tools", "LLM", "Agents"],
  "developer-tools": ["Developer Tools", "Developer Experience", "Frontend Platform", "SDK"],
  "defense-tech": ["Mission Software Engineer", "Human-Machine Interface Engineer", "Visualization Engineer", "Operator Tools"],
  geospatial: ["Geospatial", "Mapping", "Visualization", "Data Visualization"],
  "enterprise-saas": ["Admin Console", "Enterprise UI", "Workflow", "Dashboard"],
  fintech: ["Payments", "Risk", "Financial Infrastructure", "Admin Tools"],
  "data-visualization": ["Visualization Engineer", "Data Visualization", "Dashboard", "Analytics"],
  "design-systems": ["Design Systems Engineer", "Frontend Platform", "Component Library", "Storybook"],
  "big-tech": ["Staff Software Engineer", "Frontend Infrastructure", "Product Engineer", "Developer Experience"],
  cloud: ["Cloud Platform", "Infrastructure UI", "Developer Tools", "Observability"],
  infrastructure: ["Platform", "Infrastructure", "SDK", "Developer Experience"],
  fraud: ["Fraud", "Risk", "Trust and Safety", "Identity Verification"],
  compliance: ["Compliance", "Risk", "Audit", "Admin Console"],
  climate: ["Climate", "Energy", "Carbon", "Grid", "Data Visualization"],
  energy: ["Energy", "Grid", "Renewables", "Climate Software", "Operational UI"],
};

const companyGroups: Array<{ categories: string[]; priority: 1 | 2 | 3; names: string[] }> = [
  {
    priority: 1,
    categories: ["highest-priority"],
    names: [
      "1Password",
      "Anduril",
      "Palantir",
      "Socure",
      "Vercel",
      "OpenAI",
      "Anthropic",
      "Cursor",
      "Replit",
      "GitHub",
      "GitLab",
      "Linear",
      "Retool",
      "Vanta",
      "Snyk",
      "Wiz",
      "Cloudflare",
      "Datadog",
      "Veeva",
      "Stripe",
      "Plaid",
      "Ramp",
      "Brex",
      "Rippling",
      "Gusto",
      "Figma",
      "Notion",
      "Airtable",
      "Canva",
      "Docker",
      "Canonical",
      "HashiCorp",
      "Supabase",
      "PlanetScale",
      "Neon",
      "Clerk",
      "WorkOS",
      "Stytch",
      "Okta",
      "Yubico",
      "Keeper Security",
      "Bitwarden",
      "Dashlane",
      "Sentry",
      "PostHog",
      "Grafana Labs",
      "Elastic",
      "Confluent",
      "Snowflake",
      "MongoDB",
      "Databricks",
    ],
  },
  {
    priority: 1,
    categories: ["security", "identity", "enterprise-saas"],
    names: [
      "1Password",
      "Yubico",
      "Okta",
      "Auth0",
      "Duo Security",
      "Ping Identity",
      "SailPoint",
      "CyberArk",
      "Keeper Security",
      "Bitwarden",
      "Dashlane",
      "Nord Security",
      "Proton",
      "Tailscale",
      "Teleport",
      "Cloudflare",
      "Fastly",
      "Zscaler",
      "Netskope",
      "Palo Alto Networks",
      "Wiz",
      "Orca Security",
      "Lacework",
      "Snyk",
      "Semgrep",
      "Socket",
      "Chainguard",
      "Anchore",
      "Aqua Security",
      "Tenable",
      "Rapid7",
      "CrowdStrike",
      "SentinelOne",
      "Huntress",
      "Drata",
      "Vanta",
      "Secureframe",
      "Thoropass",
      "OneTrust",
      "Beyond Identity",
      "Stytch",
      "WorkOS",
      "Clerk",
      "Descope",
      "FusionAuth",
      "Ory",
    ],
  },
  {
    priority: 1,
    categories: ["ai", "developer-tools"],
    names: [
      "OpenAI",
      "Anthropic",
      "Perplexity",
      "Mistral AI",
      "Cohere",
      "Hugging Face",
      "Scale AI",
      "Labelbox",
      "Dataiku",
      "Weights & Biases",
      "Runway",
      "Synthesia",
      "ElevenLabs",
      "AssemblyAI",
      "Deepgram",
      "Writer",
      "Harvey",
      "Hebbia",
      "Glean",
      "Moveworks",
      "Intercom",
      "Sierra",
      "Cognition",
      "Cursor",
      "Replit",
      "Sourcegraph",
      "Windsurf",
      "Tabnine",
      "Modal",
      "Anyscale",
      "Together AI",
      "Fireworks AI",
      "Replicate",
      "Baseten",
      "LangChain",
      "LlamaIndex",
      "Pinecone",
      "Weaviate",
      "Qdrant",
      "Braintrust",
    ],
  },
  {
    priority: 1,
    categories: ["developer-tools", "cloud", "data-visualization"],
    names: [
      "GitHub",
      "GitLab",
      "Docker",
      "Vercel",
      "Netlify",
      "Cloudflare",
      "Fastly",
      "Fly.io",
      "Render",
      "Railway",
      "DigitalOcean",
      "AWS",
      "Google Cloud",
      "Microsoft Azure",
      "Canonical",
      "Red Hat",
      "HashiCorp",
      "Pulumi",
      "Temporal",
      "Tailscale",
      "PlanetScale",
      "Neon",
      "Supabase",
      "Cockroach Labs",
      "MongoDB",
      "Redis",
      "Elastic",
      "Confluent",
      "Databricks",
      "Snowflake",
      "ClickHouse",
      "Grafana Labs",
      "Datadog",
      "New Relic",
      "Honeycomb",
      "Sentry",
      "PostHog",
      "Amplitude",
      "LaunchDarkly",
      "Linear",
      "Atlassian",
      "JetBrains",
      "CircleCI",
      "Buildkite",
      "Harness",
      "Nx",
      "Chromatic",
      "Storybook",
    ],
  },
  {
    priority: 2,
    categories: ["enterprise-saas", "internal-tools"],
    names: [
      "Salesforce",
      "ServiceNow",
      "Workday",
      "Adobe",
      "HubSpot",
      "Zendesk",
      "Freshworks",
      "Asana",
      "Monday.com",
      "ClickUp",
      "Smartsheet",
      "Notion",
      "Airtable",
      "Coda",
      "Miro",
      "Figma",
      "Canva",
      "Dropbox",
      "Box",
      "DocuSign",
      "Ironclad",
      "Carta",
      "Rippling",
      "Gusto",
      "Deel",
      "Remote",
      "Greenhouse",
      "Lever",
      "Ashby",
      "Gem",
      "BambooHR",
      "Navan",
      "Brex",
      "Ramp",
      "Mercury",
      "Bill.com",
      "Salesloft",
      "Outreach",
      "Gong",
      "Braze",
      "Iterable",
      "Klaviyo",
      "Twilio",
      "Zapier",
      "Workato",
      "Retool",
      "Appsmith",
      "Superblocks",
    ],
  },
  {
    priority: 2,
    categories: ["big-tech", "cloud", "developer-tools"],
    names: [
      "Google",
      "Meta",
      "Apple",
      "Amazon",
      "Microsoft",
      "Netflix",
      "Nvidia",
      "AMD",
      "Intel",
      "Qualcomm",
      "Cisco",
      "Dell",
      "HP",
      "Oracle",
      "IBM",
      "Adobe",
      "Salesforce",
      "VMware",
      "Broadcom",
      "Akamai",
      "Heroku",
      "Linode",
      "SUSE",
      "Atlassian",
      "Postman",
      "Apollo GraphQL",
      "Warp",
      "Prisma",
      "Doppler",
      "Clerk",
      "Auth0",
      "Okta",
    ],
  },
  {
    priority: 1,
    categories: ["ai", "developer-tools", "infrastructure"],
    names: [
      "Groq",
      "Cerebras",
      "RunPod",
      "Chroma",
      "Character.AI",
      "Jasper",
      "Glean",
      "Harvey",
      "Writer",
      "Notion",
      "Airtable",
      "Retool",
      "Apollo GraphQL",
      "Warp",
      "Prisma",
      "Clerk",
      "WorkOS",
      "Doppler",
      "Tailscale",
    ],
  },
  {
    priority: 2,
    categories: ["fintech", "security", "enterprise-saas"],
    names: [
      "Stripe",
      "Plaid",
      "Block",
      "Adyen",
      "Wise",
      "Revolut",
      "Chime",
      "SoFi",
      "Robinhood",
      "Coinbase",
      "Kraken",
      "Gemini",
      "Circle",
      "Fireblocks",
      "Chainalysis",
      "Alchemy",
      "Paxos",
      "PayPal",
      "Affirm",
      "Klarna",
      "Marqeta",
      "Lithic",
      "Modern Treasury",
      "Mercury",
      "Brex",
      "Ramp",
      "Pilot",
      "TaxBit",
      "Carta",
      "AngelList",
      "Uniswap Labs",
      "Consensys",
      "Avara",
      "dYdX",
      "Chainlink Labs",
      "Anchorage Digital",
      "Ripple",
      "Checkout.com",
      "Base",
    ],
  },
  {
    priority: 1,
    categories: ["security", "identity", "fraud", "compliance"],
    names: [
      "Abnormal Security",
      "Material Security",
      "Axiom",
      "Panther",
      "Tines",
      "Torq",
      "Island",
      "Kolide",
      "Alloy",
      "Persona",
      "Trulioo",
      "Onfido",
      "Jumio",
      "Arkose Labs",
      "TRM Labs",
      "Elliptic",
      "Socure",
      "Chainalysis",
      "Beyond Identity",
      "Teleport",
      "Chainguard",
    ],
  },
  {
    priority: 1,
    categories: ["defense-tech", "geospatial", "data-visualization"],
    names: [
      "Anduril",
      "Palantir",
      "Shield AI",
      "Saronic",
      "Epirus",
      "Vannevar Labs",
      "Rebellion Defense",
      "Helsing",
      "Skydio",
      "AeroVironment",
      "Applied Intuition",
      "Scale AI",
      "Primer",
      "Govini",
      "Second Front Systems",
      "BlackSky",
      "Planet",
      "Maxar",
      "Capella Space",
      "Umbra",
      "Cesium",
      "Esri",
      "Mapbox",
      "CARTO",
      "Blue Origin",
      "SpaceX",
      "Rocket Lab",
      "Astranis",
      "Northrop Grumman",
      "Lockheed Martin",
      "RTX",
      "Boeing",
      "General Dynamics",
      "Leidos",
      "SAIC",
      "Booz Allen Hamilton",
      "CACI",
      "Parsons",
      "BAE Systems",
      "Thales",
      "Airbus Defence",
      "Rheinmetall",
      "Saab",
      "Kongsberg",
      "Saildrone",
      "Relativity Space",
      "Sierra Space",
      "Amentum",
      "L3Harris",
      "ManTech",
      "Peraton",
      "Leonardo",
      "Gecko Robotics",
      "Hadrian",
      "Mach Industries",
      "Castelion",
      "Forterra",
      "Red 6",
      "Firestorm Labs",
      "Neros Technologies",
    ],
  },
  {
    priority: 2,
    categories: ["design-systems", "developer-tools"],
    names: [
      "Figma",
      "Canva",
      "Adobe",
      "Webflow",
      "Framer",
      "Spline",
      "Rive",
      "Miro",
      "Notion",
      "Coda",
      "Airtable",
      "Pitch",
      "ReadMe",
      "Mintlify",
      "Chromatic",
      "Storybook",
      "Zeroheight",
      "Zeplin",
      "Builder.io",
      "Plasmic",
      "Sanity",
      "Contentful",
      "Prismic",
      "Strapi",
      "Vercel",
      "Netlify",
      "Shopify",
    ],
  },
  {
    priority: 3,
    categories: ["health-tech", "enterprise-saas", "data-visualization"],
    names: [
      "Omada Health",
      "Noom",
      "Ro",
      "Hims & Hers",
      "Levels",
      "Function Health",
      "Maven Clinic",
      "Cedar",
      "Oscar Health",
      "Devoted Health",
      "One Medical",
      "Aledade",
      "Komodo Health",
      "Flatiron Health",
      "Tempus",
      "Verily",
      "Benchling",
      "Veeva",
      "Modern Health",
      "Headspace",
      "Spring Health",
      "Lyra Health",
      "GoodRx",
      "Doximity",
      "Zocdoc",
    ],
  },
  {
    priority: 2,
    categories: ["data-visualization", "analytics", "enterprise-saas"],
    names: [
      "Databricks",
      "Snowflake",
      "Tableau",
      "Looker",
      "Mode",
      "Hex",
      "Sigma Computing",
      "ThoughtSpot",
      "Metabase",
      "dbt Labs",
      "Fivetran",
      "Airbyte",
      "RudderStack",
      "Segment",
      "Heap",
      "Amplitude",
      "Mixpanel",
      "PostHog",
      "FullStory",
      "Pendo",
      "Productboard",
      "Hightouch",
      "MotherDuck",
      "ClickHouse",
      "Starburst",
      "Monte Carlo",
      "Atlan",
      "Alation",
      "Collibra",
    ],
  },
  {
    priority: 2,
    categories: ["remote-friendly", "europe"],
    names: [
      "Canonical",
      "GitLab",
      "Automattic",
      "Toggl",
      "Hotjar",
      "Miro",
      "Wise",
      "Revolut",
      "Monzo",
      "N26",
      "Mollie",
      "Adyen",
      "Personio",
      "Celonis",
      "Staffbase",
      "Contentful",
      "Sanity",
      "Prismic",
      "Storyblok",
      "Typeform",
      "DeepL",
      "Mistral AI",
      "Hugging Face",
      "Synthesia",
      "ElevenLabs",
      "Snyk",
      "Tailscale",
      "Grafana Labs",
      "Elastic",
      "Redis",
      "Docker",
      "JetBrains",
      "Aiven",
      "Supermetrics",
      "Wolt",
      "Bolt",
      "Klarna",
      "Spotify",
      "Unity",
      "Trustpilot",
      "Remote",
      "Deel",
      "Oyster",
      "Helsing",
      "Rheinmetall",
      "Saab",
      "Kongsberg",
      "Airbus",
      "DeepL",
      "The Browser Company",
      "Celonis",
      "Malt",
      "Honeypot",
      "OfferZen",
      "No Fluff Jobs",
      "Landing.jobs",
    ],
  },
  {
    priority: 3,
    categories: ["climate", "energy", "data-visualization"],
    names: [
      "Watershed",
      "Arcadia",
      "Patch",
      "Persefoni",
      "Palmetto",
      "Span",
      "Form Energy",
      "Redwood Materials",
      "Commonwealth Fusion Systems",
      "Twelve",
      "Heirloom",
      "Charm Industrial",
      "Watershed",
    ],
  },
];

const atsSlugOverrides: Record<string, CompanySource["atsSlugs"]> = {
  "1Password": { greenhouse: ["1password"] },
  Anduril: { greenhouse: ["andurilindustries", "anduril"] },
  Anthropic: { greenhouse: ["anthropic"] },
  Ashby: { ashby: ["ashby"] },
  Airtable: { greenhouse: ["airtable"] },
  Brex: { greenhouse: ["brex"] },
  Canva: { greenhouse: ["canva"] },
  Canonical: { greenhouse: ["canonical"] },
  Cloudflare: { greenhouse: ["cloudflare"] },
  Cursor: { greenhouse: ["cursor"] },
  Datadog: { greenhouse: ["datadog"] },
  Docker: { greenhouse: ["docker"] },
  Figma: { greenhouse: ["figma"] },
  GitHub: { greenhouse: ["github"] },
  GitLab: { greenhouse: ["gitlab"] },
  "Grafana Labs": { greenhouse: ["grafana"] },
  HashiCorp: { greenhouse: ["hashicorp"] },
  "Hugging Face": { greenhouse: ["huggingface"] },
  Linear: { greenhouse: ["linear"] },
  "Mistral AI": { greenhouse: ["mistral"] },
  Notion: { greenhouse: ["notion"] },
  Okta: { greenhouse: ["okta"] },
  OpenAI: { greenhouse: ["openai"] },
  Palantir: { greenhouse: ["palantir"] },
  Perplexity: { greenhouse: ["perplexityai"] },
  Ramp: { greenhouse: ["ramp"] },
  Replit: { greenhouse: ["replit"] },
  Rippling: { greenhouse: ["rippling"] },
  "Scale AI": { greenhouse: ["scaleai"] },
  Stripe: { greenhouse: ["stripe"] },
  Supabase: { greenhouse: ["supabase"] },
  Vercel: { greenhouse: ["vercel"] },
  Veeva: { greenhouse: ["veeva"] },
  Vanta: { greenhouse: ["vanta"] },
  WorkOS: { greenhouse: ["workos"] },
  Yubico: { greenhouse: ["yubico"] },
};

export const companySources: CompanySource[] = Array.from(buildCompanySources().values()).sort((a, b) =>
  a.priority - b.priority || a.name.localeCompare(b.name),
);

export const companySourceSearchTags = [
  "react",
  "typescript",
  "nextjs",
  "full-stack",
  "frontend-platform",
  "design-systems",
  "storybook",
  "testing",
  "jest",
  "playwright",
  "mui",
  "admin-console",
  "enterprise-saas",
  "security",
  "identity",
  "auth",
  "webauthn",
  "passkeys",
  "developer-tools",
  "ai-product",
  "ai-agents",
  "structured-outputs",
  "cloud",
  "infrastructure",
  "internal-tools",
  "risk",
  "fraud",
  "compliance",
  "data-visualization",
  "dashboard",
  "mission-software",
  "defense-tech",
  "geospatial",
  "climate",
  "energy",
  "remote",
];

export const companySourceDownrankTerms = [
  "native mobile only",
  "ios only",
  "android only",
  "embedded only",
  "firmware only",
  "ml research scientist",
  "quantitative researcher",
  "sales engineer only",
  "solutions engineer only",
  "wordpress only",
  "php only",
  "junior",
  "new grad",
  "clearance required",
  "onsite only",
];

function buildCompanySources() {
  const companies = new Map<string, CompanySource>();

  for (const group of companyGroups) {
    for (const name of group.names) {
      const existing = companies.get(name);
      const categories = uniq([...(existing?.categories ?? []), ...group.categories]);
      companies.set(name, {
        name,
        categories,
        priority: existing ? Math.min(existing.priority, group.priority) as 1 | 2 | 3 : group.priority,
        searchTerms: termsFor(categories),
        careersQuery: `${name} careers senior frontend engineer React TypeScript`,
        atsSlugs: atsSlugOverrides[name] ?? generatedAtsSlugs(name),
      });
    }
  }

  return companies;
}

export function createCompanySource(input: {
  name: string;
  categories: string[];
  priority: 1 | 2 | 3;
  atsSlugs?: CompanySource["atsSlugs"];
}): CompanySource {
  const categories = uniq(input.categories.length ? input.categories : ["custom"]);
  return {
    name: input.name,
    categories,
    priority: input.priority,
    searchTerms: termsFor(categories),
    careersQuery: `${input.name} careers senior frontend engineer React TypeScript`,
    atsSlugs: input.atsSlugs && Object.keys(input.atsSlugs).length ? input.atsSlugs : generatedAtsSlugs(input.name),
  };
}

function termsFor(categories: string[]) {
  return uniq([
    ...defaultSearchTerms,
    ...categories.flatMap((category) => categoryTerms[category] ?? []),
  ]);
}

function generatedAtsSlugs(name: string): CompanySource["atsSlugs"] {
  const compact = name
    .toLowerCase()
    .replace(/\s*\/\s*/g, " ")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .join("");
  const dashed = name
    .toLowerCase()
    .replace(/\s*\/\s*/g, " ")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return { greenhouse: uniq([compact, dashed]), lever: uniq([compact, dashed]), ashby: uniq([compact, dashed]) };
}

function uniq<T>(items: T[]) {
  return Array.from(new Set(items));
}
