"use client";

import AutoAwesomeOutlinedIcon from "@mui/icons-material/AutoAwesomeOutlined";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Chip from "@mui/material/Chip";
import Divider from "@mui/material/Divider";
import LinearProgress from "@mui/material/LinearProgress";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { useRouter } from "next/navigation";
import { useState } from "react";

type SuggestedProfile = {
  name: string;
  searchIntent: string;
  remotePreference: string;
  relocationPreference: string;
  titles: string[];
  jobTypes: string[];
  countries: string[];
  salaryCurrency: string;
  salaryMin: number | null;
  industries: string[];
  keywordsRequired: string[];
  keywordsPreferred: string[];
  keywordsExcluded: string[];
  excludedCompanies: string[];
  minimumMatchScore: number;
  rationale: string;
  evidence: string[];
  githubEvidence: string[];
  alreadyExists?: boolean;
};

type SuggestResponse = {
  generatedBy: string;
  githubRepositoriesConsidered: number;
  verifiedBulletsConsidered: number;
  suggestions: SuggestedProfile[];
  error?: string;
};

export function ProfileSuggestionPanel() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [creating, setCreating] = useState("");
  const [response, setResponse] = useState<SuggestResponse | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  async function scan() {
    setLoading(true);
    setError("");
    setNotice("");
    const result = await fetch("/api/profiles/suggest", { method: "POST" });
    const body = (await result.json()) as SuggestResponse;
    setLoading(false);

    if (!result.ok) {
      setError(body.error ?? "Unable to suggest profiles.");
      return;
    }

    setResponse(body);
  }

  async function createProfile(suggestion: SuggestedProfile) {
    setCreating(suggestion.name);
    setError("");
    setNotice("");
    const result = await fetch("/api/profiles", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        name: suggestion.name,
        searchIntent: suggestion.searchIntent,
        remotePreference: suggestion.remotePreference,
        relocationPreference: suggestion.relocationPreference,
        salaryCurrency: suggestion.salaryCurrency,
        salaryMin: suggestion.salaryMin,
        includeUnknownSalary: true,
        minimumMatchScore: suggestion.minimumMatchScore,
        maxResultsPerRun: 50,
        titles: suggestion.titles,
        jobTypes: suggestion.jobTypes,
        countries: suggestion.countries,
        industries: suggestion.industries,
        keywordsRequired: suggestion.keywordsRequired,
        keywordsPreferred: suggestion.keywordsPreferred,
        keywordsExcluded: suggestion.keywordsExcluded,
        excludedCompanies: suggestion.excludedCompanies,
      }),
    });
    const body = await result.json().catch(() => ({}));
    setCreating("");

    if (!result.ok) {
      setError(body.error ?? "Unable to create suggested profile.");
      return;
    }

    setNotice(`Created "${suggestion.name}".`);
    setResponse((current) => current
      ? {
          ...current,
          suggestions: current.suggestions.map((item) => item.name === suggestion.name ? { ...item, alreadyExists: true } : item),
        }
      : current);
    router.refresh();
  }

  return (
    <Card>
      <CardContent>
        <Stack spacing={2}>
          <Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ justifyContent: "space-between", alignItems: { md: "center" } }}>
            <Box>
              <Typography variant="h3">AI opportunity scan</Typography>
              <Typography variant="body2" color="text.secondary">
                Scan your approved resume profile and synced GitHub work to propose search profiles you may be overlooking.
              </Typography>
            </Box>
            <Button variant="contained" startIcon={<AutoAwesomeOutlinedIcon />} disabled={loading} onClick={scan}>
              {loading ? "Scanning..." : "Suggest profiles"}
            </Button>
          </Stack>
          {loading ? <LinearProgress /> : null}
          {error ? <Alert severity="error">{error}</Alert> : null}
          {notice ? <Alert severity="success">{notice}</Alert> : null}
          {response ? (
            <Alert severity="info">
              Considered {response.verifiedBulletsConsidered} verified bullets and {response.githubRepositoriesConsidered} GitHub repositories. Generated by {response.generatedBy}.
            </Alert>
          ) : null}
          {response?.suggestions.length ? (
            <Stack spacing={1.5}>
              {response.suggestions.map((suggestion) => (
                <Box key={suggestion.name} sx={{ border: 1, borderColor: "divider", borderRadius: 1, p: 1.5, bgcolor: suggestion.alreadyExists ? "#f8fafc" : "#ffffff" }}>
                  <Stack spacing={1.25}>
                    <Stack direction={{ xs: "column", md: "row" }} spacing={1} sx={{ justifyContent: "space-between", alignItems: { md: "flex-start" } }}>
                      <Box>
                        <Stack direction="row" spacing={1} sx={{ alignItems: "center", flexWrap: "wrap" }}>
                          <Typography sx={{ fontWeight: 900 }}>{suggestion.name}</Typography>
                          {suggestion.alreadyExists ? <Chip size="small" label="Already exists" /> : null}
                          <Chip size="small" color="primary" variant="outlined" label={`${suggestion.minimumMatchScore}+`} />
                        </Stack>
                        <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>{suggestion.rationale}</Typography>
                      </Box>
                      <Button
                        variant="outlined"
                        disabled={suggestion.alreadyExists || creating === suggestion.name}
                        onClick={() => void createProfile(suggestion)}
                      >
                        {creating === suggestion.name ? "Creating..." : "Create profile"}
                      </Button>
                    </Stack>
                    <Stack direction="row" spacing={0.75} useFlexGap sx={{ flexWrap: "wrap" }}>
                      {[...suggestion.titles.slice(0, 5), ...suggestion.keywordsPreferred.slice(0, 8)].map((item, index) => (
                        <Chip key={`${suggestion.name}-${item}-${index}`} size="small" variant="outlined" label={item} />
                      ))}
                    </Stack>
                    <Divider />
                    <Evidence title="Resume evidence" items={suggestion.evidence} />
                    <Evidence title="GitHub evidence" items={suggestion.githubEvidence} />
                  </Stack>
                </Box>
              ))}
            </Stack>
          ) : null}
        </Stack>
      </CardContent>
    </Card>
  );
}

function Evidence({ title, items }: { title: string; items: string[] }) {
  if (!items.length) return null;
  return (
    <Box>
      <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 850, textTransform: "uppercase" }}>{title}</Typography>
      <Stack spacing={0.5} sx={{ mt: 0.5 }}>
        {items.slice(0, 4).map((item, index) => (
          <Typography key={`${title}-${item}-${index}`} variant="body2" color="text.secondary">- {item}</Typography>
        ))}
      </Stack>
    </Box>
  );
}
